# 기본 이미지 설정
FROM python:3.11.6

# 작업 디렉토리 설정
WORKDIR /app

# 의존성 파일 복사 및 설치
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 애플리케이션 코드 복사
COPY . .

# wsgi gunicorn 사용 + nginx / 2개의 워커, 4개의 쓰레드 => 약 8개 병렬처리
CMD ["gunicorn", "-w", "2", "--threads", "4", "-b", "0.0.0.0:5000", "app:app"]

